import {
  User,
  Provider,
  ServiceCategory,
  Booking,
  Review,
  Complaint,
  AppNotification
} from '../types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-cust-1',
    name: 'Payal Sharma',
    email: 'customer@servicehub.com',
    phone: '+91 98765 43210',
    role: 'CUSTOMER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user-cust-2',
    name: 'Amit Verma',
    email: 'amit.verma@gmail.com',
    phone: '+91 98111 22334',
    role: 'CUSTOMER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    createdAt: '2026-02-12T14:30:00Z',
  },
  {
    id: 'user-cust-3',
    name: 'Rahul Singhania',
    email: 'rahul.s@outlook.com',
    phone: '+91 98222 33445',
    role: 'CUSTOMER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    createdAt: '2026-03-01T09:15:00Z',
  },
  {
    id: 'user-cust-4',
    name: 'Priya Patel',
    email: 'priya.patel@gmail.com',
    phone: '+91 98333 44556',
    role: 'CUSTOMER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    createdAt: '2026-03-05T11:45:00Z',
  },
  {
    id: 'user-prov-1',
    name: 'Raj Kumar',
    email: 'provider@servicehub.com',
    phone: '+91 98991 12233',
    role: 'PROVIDER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    createdAt: '2026-01-05T08:00:00Z',
  },
  {
    id: 'user-prov-2',
    name: 'Suresh Electricals',
    email: 'suresh.electricals@gmail.com',
    phone: '+91 98770 12345',
    role: 'PROVIDER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    createdAt: '2026-01-15T10:20:00Z',
  },
  {
    id: 'user-prov-3',
    name: 'Vikram Plumbing Works',
    email: 'vikram.plumbing@gmail.com',
    phone: '+91 98555 66778',
    role: 'PROVIDER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    createdAt: '2026-01-18T12:00:00Z',
  },
  {
    id: 'user-prov-4',
    name: 'Manoj Joshi',
    email: 'manoj.itcare@gmail.com',
    phone: '+91 98444 55667',
    role: 'PROVIDER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    createdAt: '2026-02-01T15:10:00Z',
  },
  {
    id: 'user-prov-5',
    name: 'Anita Devi Cleaning Services',
    email: 'anita.cleanings@gmail.com',
    phone: '+91 98333 11223',
    role: 'PROVIDER',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    createdAt: '2026-02-10T09:00:00Z',
  },
  {
    id: 'user-admin-1',
    name: 'Admin ServiceHub',
    email: 'admin@servicehub.com',
    phone: '+91 99999 88888',
    role: 'ADMIN',
    status: 'ACTIVE',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
    createdAt: '2026-01-01T00:00:00Z',
  },
];

export const MOCK_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-1',
    slug: 'electrician',
    name: 'Electrician',
    description: 'Switches, wiring, MCB tripping, ceiling fans, appliance installations, and power backups.',
    basePrice: 499,
    iconName: 'Zap',
    providerCount: 18,
    active: true,
  },
  {
    id: 'cat-2',
    slug: 'plumber',
    name: 'Plumber',
    description: 'Pipe leaks, taps, flush tanks, geyser fittings, bathroom fittings, and drain blockages.',
    basePrice: 399,
    iconName: 'Wrench',
    providerCount: 14,
    active: true,
  },
  {
    id: 'cat-3',
    slug: 'ac-repair',
    name: 'AC Repair',
    description: 'Split and window AC cooling check, gas refilling, jet cleaning, PCB repair, and installation.',
    basePrice: 699,
    iconName: 'Wind',
    providerCount: 22,
    active: true,
  },
  {
    id: 'cat-4',
    slug: 'laptop-repair',
    name: 'Laptop Repair',
    description: 'Hardware diagnostics, screen replacement, battery issues, OS installation, and motherboard repair.',
    basePrice: 599,
    iconName: 'Laptop',
    providerCount: 12,
    active: true,
  },
  {
    id: 'cat-5',
    slug: 'cleaning',
    name: 'Deep Cleaning',
    description: 'Home deep sanitization, bathroom floor scrub, sofa & carpet shampoo, kitchen grease removal.',
    basePrice: 899,
    iconName: 'Sparkles',
    providerCount: 16,
    active: true,
  },
];

export const MOCK_PROVIDERS: Provider[] = [
  {
    id: 'prov-1',
    userId: 'user-prov-1',
    name: 'Raj AC & Cooling Tech',
    email: 'provider@servicehub.com',
    phone: '+91 98991 12233',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    verified: true,
    verificationStatus: 'VERIFIED',
    rating: 4.8,
    jobCount: 142,
    experienceYears: 7,
    bio: 'Certified HVAC & refrigeration technician with 7+ years of experience across Daikin, Voltas, LG, and Blue Star units. Specializing in rapid diagnosis and genuine spares.',
    primaryCategory: 'AC Repair',
    startingPrice: 699,
    status: 'ACTIVE',
    createdAt: '2026-01-05T08:00:00Z',
    services: [
      {
        id: 'ps-101',
        categoryId: 'cat-3',
        categoryName: 'AC Repair',
        title: 'AC Jet Cleaning & Filter Wash',
        basePrice: 699,
        description: 'Comprehensive high-pressure jet cleaning of outdoor and indoor cooling coils.',
        active: true,
      },
      {
        id: 'ps-102',
        categoryId: 'cat-3',
        categoryName: 'AC Repair',
        title: 'AC Gas Top-Up & Cooling Diagnosis',
        basePrice: 1299,
        description: 'Full leak test with nitrogen, vacuum flush, and R32/R410A gas top-up.',
        active: true,
      },
      {
        id: 'ps-103',
        categoryId: 'cat-1',
        categoryName: 'Electrician',
        title: 'AC Power Point & Stabilizer Setup',
        basePrice: 499,
        description: 'Heavy duty 16A modular socket wiring and stabilizer mounting.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-1', city: 'Mathura', area: 'Krishna Nagar', pincode: '281001' },
      { id: 'sa-2', city: 'Mathura', area: 'Highway & Refinery Road', pincode: '281004' },
      { id: 'sa-3', city: 'Vrindavan', area: 'Raman Reti', pincode: '281121' },
    ],
    availability: {
      monday: { available: true, startTime: '09:00', endTime: '19:00' },
      tuesday: { available: true, startTime: '09:00', endTime: '19:00' },
      wednesday: { available: true, startTime: '09:00', endTime: '19:00' },
      thursday: { available: true, startTime: '09:00', endTime: '19:00' },
      friday: { available: true, startTime: '09:00', endTime: '19:00' },
      saturday: { available: true, startTime: '10:00', endTime: '18:00' },
      sunday: { available: false, startTime: '09:00', endTime: '13:00' },
    },
  },
  {
    id: 'prov-2',
    userId: 'user-prov-2',
    name: 'Suresh Electricals & Solutions',
    email: 'suresh.electricals@gmail.com',
    phone: '+91 98770 12345',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    verified: true,
    verificationStatus: 'VERIFIED',
    rating: 4.9,
    jobCount: 189,
    experienceYears: 10,
    bio: 'Government licensed master electrician. Expert in inverter wiring, MCB replacement, chandelier installation, and solving hazardous short circuits.',
    primaryCategory: 'Electrician',
    startingPrice: 499,
    status: 'ACTIVE',
    createdAt: '2026-01-15T10:20:00Z',
    services: [
      {
        id: 'ps-201',
        categoryId: 'cat-1',
        categoryName: 'Electrician',
        title: 'General Wiring & Short Circuit Fix',
        basePrice: 499,
        description: 'Complete fault tracing and neutral wire repair with safety inspection.',
        active: true,
      },
      {
        id: 'ps-202',
        categoryId: 'cat-1',
        categoryName: 'Electrician',
        title: 'Inverter & Battery Setup',
        basePrice: 799,
        description: 'Heavy duty backup inverter installation, wiring and battery acid check.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-4', city: 'Mathura', area: 'Dampier Nagar', pincode: '281001' },
      { id: 'sa-5', city: 'Mathura', area: 'Vikas Nagar', pincode: '281006' },
      { id: 'sa-6', city: 'Agra', area: 'Sanjay Place', pincode: '282002' },
    ],
    availability: {
      monday: { available: true, startTime: '08:30', endTime: '20:00' },
      tuesday: { available: true, startTime: '08:30', endTime: '20:00' },
      wednesday: { available: true, startTime: '08:30', endTime: '20:00' },
      thursday: { available: true, startTime: '08:30', endTime: '20:00' },
      friday: { available: true, startTime: '08:30', endTime: '20:00' },
      saturday: { available: true, startTime: '09:00', endTime: '18:00' },
      sunday: { available: true, startTime: '10:00', endTime: '14:00' },
    },
  },
  {
    id: 'prov-3',
    userId: 'user-prov-3',
    name: 'Vikram Express Plumbing',
    email: 'vikram.plumbing@gmail.com',
    phone: '+91 98555 66778',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    verified: true,
    verificationStatus: 'VERIFIED',
    rating: 4.7,
    jobCount: 115,
    experienceYears: 6,
    bio: 'Professional plumber specializing in overhead water tank connection, concealed CPVC pipe repair, sensor faucets, and pressure motor installations.',
    primaryCategory: 'Plumber',
    startingPrice: 399,
    status: 'ACTIVE',
    createdAt: '2026-01-18T12:00:00Z',
    services: [
      {
        id: 'ps-301',
        categoryId: 'cat-2',
        categoryName: 'Plumber',
        title: 'Tap & Shower Leakage Repair',
        basePrice: 399,
        description: 'Washers, ceramic cartidges, spindle replacement and leak-proof sealing.',
        active: true,
      },
      {
        id: 'ps-302',
        categoryId: 'cat-2',
        categoryName: 'Plumber',
        title: 'Water Tank & Booster Pump Installation',
        basePrice: 1199,
        description: 'PVC manifold connections, float valves, and automatic water controller.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-7', city: 'Mathura', area: 'Krishna Nagar', pincode: '281001' },
      { id: 'sa-8', city: 'Agra', area: 'Dayal Bagh', pincode: '282005' },
      { id: 'sa-9', city: 'Agra', area: 'Kamla Nagar', pincode: '282004' },
    ],
    availability: {
      monday: { available: true, startTime: '09:00', endTime: '18:00' },
      tuesday: { available: true, startTime: '09:00', endTime: '18:00' },
      wednesday: { available: true, startTime: '09:00', endTime: '18:00' },
      thursday: { available: true, startTime: '09:00', endTime: '18:00' },
      friday: { available: true, startTime: '09:00', endTime: '18:00' },
      saturday: { available: true, startTime: '09:00', endTime: '17:00' },
      sunday: { available: false, startTime: '09:00', endTime: '13:00' },
    },
  },
  {
    id: 'prov-4',
    userId: 'user-prov-4',
    name: 'Manoj QuickFix Laptop & IT',
    email: 'manoj.itcare@gmail.com',
    phone: '+91 98444 55667',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    verified: true,
    verificationStatus: 'VERIFIED',
    rating: 4.8,
    jobCount: 96,
    experienceYears: 8,
    bio: 'Hardware chip-level engineer for Dell, HP, Lenovo, MacBook and Asus laptops. On-site diagnosis, thermal paste re-application, RAM/SSD upgrades and screen repairs.',
    primaryCategory: 'Laptop Repair',
    startingPrice: 599,
    status: 'ACTIVE',
    createdAt: '2026-02-01T15:10:00Z',
    services: [
      {
        id: 'ps-401',
        categoryId: 'cat-4',
        categoryName: 'Laptop Repair',
        title: 'Doorstep Laptop Health Check & OS Tune-up',
        basePrice: 599,
        description: 'Complete thermal repaste, dust blowout, boot diagnosis and OS cleanup.',
        active: true,
      },
      {
        id: 'ps-402',
        categoryId: 'cat-4',
        categoryName: 'Laptop Repair',
        title: 'Screen & Keyboard Hardware Replacement',
        basePrice: 999,
        description: 'Original IPS display panel and backlit keyboard replacement with warranty.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-10', city: 'Delhi', area: 'Connaught Place', pincode: '110001' },
      { id: 'sa-11', city: 'Delhi', area: 'Nehru Place', pincode: '110019' },
      { id: 'sa-12', city: 'Agra', area: 'Sanjay Place', pincode: '282002' },
    ],
    availability: {
      monday: { available: true, startTime: '10:00', endTime: '19:30' },
      tuesday: { available: true, startTime: '10:00', endTime: '19:30' },
      wednesday: { available: true, startTime: '10:00', endTime: '19:30' },
      thursday: { available: true, startTime: '10:00', endTime: '19:30' },
      friday: { available: true, startTime: '10:00', endTime: '19:30' },
      saturday: { available: true, startTime: '10:00', endTime: '18:00' },
      sunday: { available: false, startTime: '10:00', endTime: '14:00' },
    },
  },
  {
    id: 'prov-5',
    userId: 'user-prov-5',
    name: 'Anita Pristine Home Cleaning',
    email: 'anita.cleanings@gmail.com',
    phone: '+91 98333 11223',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    verified: true,
    verificationStatus: 'VERIFIED',
    rating: 4.9,
    jobCount: 165,
    experienceYears: 5,
    bio: 'Professional residential and commercial sanitization crew using eco-friendly chemical disinfectants, industrial rotary scrubbers, and vacuum equipment.',
    primaryCategory: 'Deep Cleaning',
    startingPrice: 899,
    status: 'ACTIVE',
    createdAt: '2026-02-10T09:00:00Z',
    services: [
      {
        id: 'ps-501',
        categoryId: 'cat-5',
        categoryName: 'Deep Cleaning',
        title: 'Full Kitchen Deep Degreasing & Sanitization',
        basePrice: 899,
        description: 'Tiles, chimney, stove, cabinets and floor high-temperature scrub.',
        active: true,
      },
      {
        id: 'ps-502',
        categoryId: 'cat-5',
        categoryName: 'Deep Cleaning',
        title: '3BHK Complete Home Deep Clean',
        basePrice: 2499,
        description: 'Complete 3BHK scrubbing, balcony wash, bathroom descaling and sofa vacuuming.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-13', city: 'Mathura', area: 'Krishna Nagar', pincode: '281001' },
      { id: 'sa-14', city: 'Mathura', area: 'Goverdhan Road', pincode: '281004' },
      { id: 'sa-15', city: 'Vrindavan', area: 'Chaitanya Vihar', pincode: '281121' },
    ],
    availability: {
      monday: { available: true, startTime: '08:00', endTime: '18:00' },
      tuesday: { available: true, startTime: '08:00', endTime: '18:00' },
      wednesday: { available: true, startTime: '08:00', endTime: '18:00' },
      thursday: { available: true, startTime: '08:00', endTime: '18:00' },
      friday: { available: true, startTime: '08:00', endTime: '18:00' },
      saturday: { available: true, startTime: '08:00', endTime: '18:00' },
      sunday: { available: true, startTime: '09:00', endTime: '16:00' },
    },
  },
  {
    id: 'prov-6',
    userId: 'user-prov-6',
    name: 'Gaurav Cooling Hub',
    email: 'gaurav.cooling@gmail.com',
    phone: '+91 98123 78901',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    verified: true,
    verificationStatus: 'VERIFIED',
    rating: 4.6,
    jobCount: 78,
    experienceYears: 4,
    bio: 'Dedicated AC service specialist with quick dispatch across Mathura and Agra. Quality copper piping and refrigerant testing.',
    primaryCategory: 'AC Repair',
    startingPrice: 699,
    status: 'ACTIVE',
    createdAt: '2026-02-15T11:00:00Z',
    services: [
      {
        id: 'ps-601',
        categoryId: 'cat-3',
        categoryName: 'AC Repair',
        title: 'AC Routine Servicing & Gas Check',
        basePrice: 699,
        description: 'Comprehensive coil wash, drain tray clearance, and thermal sensor calibration.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-16', city: 'Mathura', area: 'Krishna Nagar', pincode: '281001' },
      { id: 'sa-17', city: 'Agra', area: 'Shahganj', pincode: '282010' },
    ],
    availability: {
      monday: { available: true, startTime: '09:00', endTime: '18:00' },
      tuesday: { available: true, startTime: '09:00', endTime: '18:00' },
      wednesday: { available: true, startTime: '09:00', endTime: '18:00' },
      thursday: { available: true, startTime: '09:00', endTime: '18:00' },
      friday: { available: true, startTime: '09:00', endTime: '18:00' },
      saturday: { available: true, startTime: '09:00', endTime: '16:00' },
      sunday: { available: false, startTime: '09:00', endTime: '12:00' },
    },
  },
  {
    id: 'prov-7',
    userId: 'user-prov-7',
    name: 'Mohan Lal Power Tech',
    email: 'mohan.power@gmail.com',
    phone: '+91 98234 56789',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    verified: true,
    verificationStatus: 'VERIFIED',
    rating: 4.7,
    jobCount: 92,
    experienceYears: 6,
    bio: 'Experienced electrician for home automation, smart switches, LED panel lighting, and industrial fuse box maintenance.',
    primaryCategory: 'Electrician',
    startingPrice: 499,
    status: 'ACTIVE',
    createdAt: '2026-02-18T10:00:00Z',
    services: [
      {
        id: 'ps-701',
        categoryId: 'cat-1',
        categoryName: 'Electrician',
        title: 'Smart Switch & Fan Installation',
        basePrice: 499,
        description: 'Mounting, neutral wiring check, and RF/Wi-Fi pairing for smart switches.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-18', city: 'Delhi', area: 'Lajpat Nagar', pincode: '110024' },
      { id: 'sa-19', city: 'Delhi', area: 'Connaught Place', pincode: '110001' },
    ],
    availability: {
      monday: { available: true, startTime: '09:00', endTime: '19:00' },
      tuesday: { available: true, startTime: '09:00', endTime: '19:00' },
      wednesday: { available: true, startTime: '09:00', endTime: '19:00' },
      thursday: { available: true, startTime: '09:00', endTime: '19:00' },
      friday: { available: true, startTime: '09:00', endTime: '19:00' },
      saturday: { available: true, startTime: '09:00', endTime: '17:00' },
      sunday: { available: true, startTime: '10:00', endTime: '15:00' },
    },
  },
  {
    id: 'prov-8',
    userId: 'user-prov-8',
    name: 'Deepak Drain & Pipe Care',
    email: 'deepak.drain@gmail.com',
    phone: '+91 98345 67890',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    verified: false,
    verificationStatus: 'PENDING',
    rating: 4.5,
    jobCount: 41,
    experienceYears: 3,
    bio: 'Drain unblocking, sewage line clearance, and pipe replacements using motorized drain snakes and pressure pumps.',
    primaryCategory: 'Plumber',
    startingPrice: 399,
    status: 'ACTIVE',
    createdAt: '2026-03-01T14:00:00Z',
    services: [
      {
        id: 'ps-801',
        categoryId: 'cat-2',
        categoryName: 'Plumber',
        title: 'Severe Drain Blockage Removal',
        basePrice: 599,
        description: 'Mechanical rotary rod clearing for blocked sinks, kitchen drains, and gully traps.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-20', city: 'Mathura', area: 'Krishna Nagar', pincode: '281001' },
      { id: 'sa-21', city: 'Vrindavan', area: 'Sunrakh Road', pincode: '281121' },
    ],
    availability: {
      monday: { available: true, startTime: '09:00', endTime: '18:00' },
      tuesday: { available: true, startTime: '09:00', endTime: '18:00' },
      wednesday: { available: true, startTime: '09:00', endTime: '18:00' },
      thursday: { available: true, startTime: '09:00', endTime: '18:00' },
      friday: { available: true, startTime: '09:00', endTime: '18:00' },
      saturday: { available: true, startTime: '09:00', endTime: '18:00' },
      sunday: { available: false, startTime: '09:00', endTime: '12:00' },
    },
  },
  {
    id: 'prov-9',
    userId: 'user-prov-9',
    name: 'Pooja Hygiene Solutions',
    email: 'pooja.hygiene@gmail.com',
    phone: '+91 98456 78901',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150',
    verified: true,
    verificationStatus: 'VERIFIED',
    rating: 4.8,
    jobCount: 104,
    experienceYears: 5,
    bio: 'Specialist in bathroom acid wash, limescale removal, water stain treatment, and sofa dry-cleaning.',
    primaryCategory: 'Deep Cleaning',
    startingPrice: 799,
    status: 'ACTIVE',
    createdAt: '2026-02-12T08:30:00Z',
    services: [
      {
        id: 'ps-901',
        categoryId: 'cat-5',
        categoryName: 'Deep Cleaning',
        title: 'Intense Bathroom Limescale & Tile Scrub',
        basePrice: 799,
        description: 'Hard water stain removal from glass partitions, tiles, taps, and sanitaryware.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-22', city: 'Agra', area: 'Fatehabad Road', pincode: '282001' },
      { id: 'sa-23', city: 'Agra', area: 'Sanjay Place', pincode: '282002' },
    ],
    availability: {
      monday: { available: true, startTime: '09:00', endTime: '17:00' },
      tuesday: { available: true, startTime: '09:00', endTime: '17:00' },
      wednesday: { available: true, startTime: '09:00', endTime: '17:00' },
      thursday: { available: true, startTime: '09:00', endTime: '17:00' },
      friday: { available: true, startTime: '09:00', endTime: '17:00' },
      saturday: { available: true, startTime: '09:00', endTime: '17:00' },
      sunday: { available: false, startTime: '09:00', endTime: '12:00' },
    },
  },
  {
    id: 'prov-10',
    userId: 'user-prov-10',
    name: 'Tarun Tech Laptop Lab',
    email: 'tarun.laptoplab@gmail.com',
    phone: '+91 98567 89012',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    verified: false,
    verificationStatus: 'PENDING',
    rating: 4.4,
    jobCount: 38,
    experienceYears: 3,
    bio: 'BGA soldering, liquid spill damage repair, motherboard component level recovery and BIOS reprogramming.',
    primaryCategory: 'Laptop Repair',
    startingPrice: 599,
    status: 'ACTIVE',
    createdAt: '2026-03-02T13:00:00Z',
    services: [
      {
        id: 'ps-1001',
        categoryId: 'cat-4',
        categoryName: 'Laptop Repair',
        title: 'Liquid Spill Recovery & Ultrasonic Board Clean',
        basePrice: 1199,
        description: 'Complete disassembly, isopropyl/ultrasonic cleaning, shorted capacitor replacement.',
        active: true,
      },
    ],
    serviceAreas: [
      { id: 'sa-24', city: 'Delhi', area: 'Karol Bagh', pincode: '110005' },
      { id: 'sa-25', city: 'Delhi', area: 'Connaught Place', pincode: '110001' },
    ],
    availability: {
      monday: { available: true, startTime: '10:00', endTime: '20:00' },
      tuesday: { available: true, startTime: '10:00', endTime: '20:00' },
      wednesday: { available: true, startTime: '10:00', endTime: '20:00' },
      thursday: { available: true, startTime: '10:00', endTime: '20:00' },
      friday: { available: true, startTime: '10:00', endTime: '20:00' },
      saturday: { available: true, startTime: '10:00', endTime: '18:00' },
      sunday: { available: false, startTime: '10:00', endTime: '14:00' },
    },
  },
];

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-1001',
    bookingNumber: 'SH-2026-001',
    customerId: 'user-cust-1',
    customer: {
      id: 'user-cust-1',
      name: 'Payal Sharma',
      email: 'customer@servicehub.com',
      phone: '+91 98765 43210',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    },
    providerId: 'prov-1',
    provider: {
      id: 'prov-1',
      name: 'Raj AC & Cooling Tech',
      email: 'provider@servicehub.com',
      phone: '+91 98991 12233',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      verified: true,
      primaryCategory: 'AC Repair',
    },
    serviceCategoryId: 'cat-3',
    serviceCategory: 'AC Repair',
    serviceTitle: 'AC Jet Cleaning & Filter Wash',
    description: 'Split AC blowing warm air and creating a humming vibration in the master bedroom.',
    date: '2026-10-02',
    time: '10:30',
    address: {
      street: 'Flat 402, Radhika Heights, Opp. BSA College Road',
      city: 'Mathura',
      area: 'Krishna Nagar',
      pincode: '281001',
      landmark: 'Near SBI Main Branch',
    },
    estimatedCost: 699,
    finalCost: 1049,
    finalCostReason: 'Outdoor condenser unit fan motor required high-grade lubrication and copper flared valve replacement.',
    finalCostStatus: 'PENDING_APPROVAL',
    paymentStatus: 'UNPAID',
    status: 'IN_PROGRESS',
    createdAt: '2026-10-01T08:00:00Z',
    updatedAt: '2026-10-01T10:45:00Z',
    timeline: [
      { status: 'PENDING', timestamp: '2026-10-01T08:00:00Z', note: 'Customer requested AC service appointment.' },
      { status: 'ACCEPTED', timestamp: '2026-10-01T08:15:00Z', note: 'Raj AC accepted request.' },
      { status: 'SCHEDULED', timestamp: '2026-10-01T08:30:00Z', note: 'Confirmed for 10:30 AM.' },
      { status: 'ON_THE_WAY', timestamp: '2026-10-01T10:00:00Z', note: 'Raj is travelling to Krishna Nagar.' },
      { status: 'IN_PROGRESS', timestamp: '2026-10-01T10:35:00Z', note: 'Work commenced. Cost update proposed.' },
    ],
  },
  {
    id: 'bk-1002',
    bookingNumber: 'SH-2026-002',
    customerId: 'user-cust-1',
    customer: {
      id: 'user-cust-1',
      name: 'Payal Sharma',
      email: 'customer@servicehub.com',
      phone: '+91 98765 43210',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    },
    providerId: 'prov-2',
    provider: {
      id: 'prov-2',
      name: 'Suresh Electricals & Solutions',
      email: 'suresh.electricals@gmail.com',
      phone: '+91 98770 12345',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
      verified: true,
      primaryCategory: 'Electrician',
    },
    serviceCategoryId: 'cat-1',
    serviceCategory: 'Electrician',
    serviceTitle: 'General Wiring & Short Circuit Fix',
    description: 'Main circuit breaker trips whenever the kitchen geyser or microwave is turned on.',
    date: '2026-10-03',
    time: '14:00',
    address: {
      street: 'Flat 402, Radhika Heights, Opp. BSA College Road',
      city: 'Mathura',
      area: 'Krishna Nagar',
      pincode: '281001',
    },
    estimatedCost: 499,
    paymentStatus: 'UNPAID',
    status: 'SCHEDULED',
    createdAt: '2026-09-30T16:00:00Z',
    updatedAt: '2026-09-30T17:15:00Z',
    timeline: [
      { status: 'PENDING', timestamp: '2026-09-30T16:00:00Z', note: 'Booking submitted.' },
      { status: 'ACCEPTED', timestamp: '2026-09-30T16:45:00Z', note: 'Suresh accepted request.' },
      { status: 'SCHEDULED', timestamp: '2026-09-30T17:15:00Z', note: 'Slot locked for 2:00 PM.' },
    ],
  },
  {
    id: 'bk-1003',
    bookingNumber: 'SH-2026-003',
    customerId: 'user-cust-1',
    customer: {
      id: 'user-cust-1',
      name: 'Payal Sharma',
      email: 'customer@servicehub.com',
      phone: '+91 98765 43210',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    },
    providerId: 'prov-3',
    provider: {
      id: 'prov-3',
      name: 'Vikram Express Plumbing',
      email: 'vikram.plumbing@gmail.com',
      phone: '+91 98555 66778',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
      verified: true,
      primaryCategory: 'Plumber',
    },
    serviceCategoryId: 'cat-2',
    serviceCategory: 'Plumber',
    serviceTitle: 'Tap & Shower Leakage Repair',
    description: 'Bathroom mixer faucet is continuously dripping from the wall joint.',
    date: '2026-09-28',
    time: '11:00',
    address: {
      street: 'Flat 402, Radhika Heights, Opp. BSA College Road',
      city: 'Mathura',
      area: 'Krishna Nagar',
      pincode: '281001',
    },
    estimatedCost: 399,
    finalCost: 399,
    finalCostStatus: 'ACCEPTED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH_RECORDED',
    paidAt: '2026-09-28T12:30:00Z',
    status: 'REVIEWED',
    createdAt: '2026-09-27T10:00:00Z',
    updatedAt: '2026-09-28T13:00:00Z',
    timeline: [
      { status: 'PENDING', timestamp: '2026-09-27T10:00:00Z' },
      { status: 'ACCEPTED', timestamp: '2026-09-27T11:00:00Z' },
      { status: 'SCHEDULED', timestamp: '2026-09-27T11:30:00Z' },
      { status: 'ON_THE_WAY', timestamp: '2026-09-28T10:45:00Z' },
      { status: 'IN_PROGRESS', timestamp: '2026-09-28T11:05:00Z' },
      { status: 'COMPLETED', timestamp: '2026-09-28T12:15:00Z' },
      { status: 'PAID', timestamp: '2026-09-28T12:30:00Z', note: 'Customer settled ₹399 in cash.' },
      { status: 'REVIEWED', timestamp: '2026-09-28T13:00:00Z', note: 'Rated 5 stars.' },
    ],
  },
  {
    id: 'bk-1004',
    bookingNumber: 'SH-2026-004',
    customerId: 'user-cust-2',
    customer: {
      id: 'user-cust-2',
      name: 'Amit Verma',
      email: 'amit.verma@gmail.com',
      phone: '+91 98111 22334',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    },
    providerId: 'prov-1',
    provider: {
      id: 'prov-1',
      name: 'Raj AC & Cooling Tech',
      email: 'provider@servicehub.com',
      phone: '+91 98991 12233',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      verified: true,
      primaryCategory: 'AC Repair',
    },
    serviceCategoryId: 'cat-3',
    serviceCategory: 'AC Repair',
    serviceTitle: 'AC Gas Top-Up & Cooling Diagnosis',
    description: 'Voltas 1.5 Ton AC not chilling during peak noon hours.',
    date: '2026-10-01',
    time: '16:00',
    address: {
      street: 'House 18, Govind Dham',
      city: 'Mathura',
      area: 'Krishna Nagar',
      pincode: '281001',
    },
    estimatedCost: 1299,
    paymentStatus: 'UNPAID',
    status: 'ACCEPTED',
    createdAt: '2026-10-01T07:30:00Z',
    updatedAt: '2026-10-01T08:00:00Z',
    timeline: [
      { status: 'PENDING', timestamp: '2026-10-01T07:30:00Z' },
      { status: 'ACCEPTED', timestamp: '2026-10-01T08:00:00Z', note: 'Provider accepted request.' },
    ],
  },
  {
    id: 'bk-1005',
    bookingNumber: 'SH-2026-005',
    customerId: 'user-cust-3',
    customer: {
      id: 'user-cust-3',
      name: 'Rahul Singhania',
      email: 'rahul.s@outlook.com',
      phone: '+91 98222 33445',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    },
    providerId: 'prov-1',
    provider: {
      id: 'prov-1',
      name: 'Raj AC & Cooling Tech',
      email: 'provider@servicehub.com',
      phone: '+91 98991 12233',
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
      verified: true,
      primaryCategory: 'AC Repair',
    },
    serviceCategoryId: 'cat-3',
    serviceCategory: 'AC Repair',
    serviceTitle: 'AC Jet Cleaning & Filter Wash',
    description: 'Annual servicing before summer season.',
    date: '2026-10-01',
    time: '18:00',
    address: {
      street: 'Bungalow 7, Highway Enclave',
      city: 'Mathura',
      area: 'Highway & Refinery Road',
      pincode: '281004',
    },
    estimatedCost: 699,
    paymentStatus: 'UNPAID',
    status: 'PENDING',
    createdAt: '2026-10-01T09:10:00Z',
    updatedAt: '2026-10-01T09:10:00Z',
    timeline: [
      { status: 'PENDING', timestamp: '2026-10-01T09:10:00Z', note: 'Awaiting provider acceptance.' },
    ],
  },
  {
    id: 'bk-1006',
    bookingNumber: 'SH-2026-006',
    customerId: 'user-cust-1',
    customer: {
      id: 'user-cust-1',
      name: 'Payal Sharma',
      email: 'customer@servicehub.com',
      phone: '+91 98765 43210',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    },
    providerId: 'prov-4',
    provider: {
      id: 'prov-4',
      name: 'Manoj QuickFix Laptop & IT',
      email: 'manoj.itcare@gmail.com',
      phone: '+91 98444 55667',
      avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
      verified: true,
      primaryCategory: 'Laptop Repair',
    },
    serviceCategoryId: 'cat-4',
    serviceCategory: 'Laptop Repair',
    serviceTitle: 'Doorstep Laptop Health Check & OS Tune-up',
    description: 'Lenovo ThinkPad overheating and shutting down while running heavy applications.',
    date: '2026-09-25',
    time: '15:30',
    address: {
      street: 'Flat 402, Radhika Heights, Opp. BSA College Road',
      city: 'Mathura',
      area: 'Krishna Nagar',
      pincode: '281001',
    },
    estimatedCost: 599,
    finalCost: 899,
    finalCostReason: 'Replaced dried thermal paste with Arctic MX-4 and cleared clogged copper heat pipe.',
    finalCostStatus: 'ACCEPTED',
    paymentStatus: 'PAID',
    paymentMethod: 'ONLINE_RECORDED',
    paidAt: '2026-09-25T17:00:00Z',
    status: 'PAID',
    createdAt: '2026-09-24T12:00:00Z',
    updatedAt: '2026-09-25T17:00:00Z',
    timeline: [
      { status: 'PENDING', timestamp: '2026-09-24T12:00:00Z' },
      { status: 'ACCEPTED', timestamp: '2026-09-24T12:30:00Z' },
      { status: 'SCHEDULED', timestamp: '2026-09-24T13:00:00Z' },
      { status: 'ON_THE_WAY', timestamp: '2026-09-25T15:00:00Z' },
      { status: 'IN_PROGRESS', timestamp: '2026-09-25T15:35:00Z' },
      { status: 'COMPLETED', timestamp: '2026-09-25T16:45:00Z' },
      { status: 'PAID', timestamp: '2026-09-25T17:00:00Z', note: 'Payment recorded in-system.' },
    ],
  },
  {
    id: 'bk-1007',
    bookingNumber: 'SH-2026-007',
    customerId: 'user-cust-4',
    customer: {
      id: 'user-cust-4',
      name: 'Priya Patel',
      email: 'priya.patel@gmail.com',
      phone: '+91 98333 44556',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    },
    providerId: 'prov-5',
    provider: {
      id: 'prov-5',
      name: 'Anita Pristine Home Cleaning',
      email: 'anita.cleanings@gmail.com',
      phone: '+91 98333 11223',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
      verified: true,
      primaryCategory: 'Deep Cleaning',
    },
    serviceCategoryId: 'cat-5',
    serviceCategory: 'Deep Cleaning',
    serviceTitle: '3BHK Complete Home Deep Clean',
    description: 'Post-renovation deep dust and paint scraping clean.',
    date: '2026-09-20',
    time: '09:00',
    address: {
      street: 'Villa 12, Vrinda Woods',
      city: 'Vrindavan',
      area: 'Chaitanya Vihar',
      pincode: '281121',
    },
    estimatedCost: 2499,
    finalCost: 2499,
    finalCostStatus: 'ACCEPTED',
    paymentStatus: 'PAID',
    paymentMethod: 'CASH_RECORDED',
    paidAt: '2026-09-20T16:00:00Z',
    status: 'REVIEWED',
    createdAt: '2026-09-18T14:00:00Z',
    updatedAt: '2026-09-20T17:00:00Z',
    timeline: [
      { status: 'PENDING', timestamp: '2026-09-18T14:00:00Z' },
      { status: 'ACCEPTED', timestamp: '2026-09-18T14:30:00Z' },
      { status: 'SCHEDULED', timestamp: '2026-09-18T15:00:00Z' },
      { status: 'ON_THE_WAY', timestamp: '2026-09-20T08:30:00Z' },
      { status: 'IN_PROGRESS', timestamp: '2026-09-20T09:10:00Z' },
      { status: 'COMPLETED', timestamp: '2026-09-20T15:45:00Z' },
      { status: 'PAID', timestamp: '2026-09-20T16:00:00Z' },
      { status: 'REVIEWED', timestamp: '2026-09-20T17:00:00Z' },
    ],
  },
  {
    id: 'bk-1008',
    bookingNumber: 'SH-2026-008',
    customerId: 'user-cust-2',
    customer: {
      id: 'user-cust-2',
      name: 'Amit Verma',
      email: 'amit.verma@gmail.com',
      phone: '+91 98111 22334',
    },
    providerId: 'prov-2',
    provider: {
      id: 'prov-2',
      name: 'Suresh Electricals & Solutions',
      email: 'suresh.electricals@gmail.com',
      phone: '+91 98770 12345',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
      verified: true,
    },
    serviceCategoryId: 'cat-1',
    serviceCategory: 'Electrician',
    serviceTitle: 'Inverter & Battery Setup',
    description: 'Customer requested cancellation due to personal emergency.',
    date: '2026-09-15',
    time: '11:00',
    address: {
      street: 'House 18, Govind Dham',
      city: 'Mathura',
      area: 'Krishna Nagar',
      pincode: '281001',
    },
    estimatedCost: 799,
    paymentStatus: 'UNPAID',
    status: 'CANCELLED',
    cancellationReason: 'Customer travelling out of city on short notice.',
    cancelledBy: 'CUSTOMER',
    createdAt: '2026-09-14T09:00:00Z',
    updatedAt: '2026-09-14T18:00:00Z',
    timeline: [
      { status: 'PENDING', timestamp: '2026-09-14T09:00:00Z' },
      { status: 'ACCEPTED', timestamp: '2026-09-14T10:00:00Z' },
      { status: 'CANCELLED', timestamp: '2026-09-14T18:00:00Z', note: 'Cancelled by customer.' },
    ],
  },
  // Additional mock bookings to ensure at least 20 bookings
  ...Array.from({ length: 12 }).map((_, idx) => {
    const bookingNum = 1009 + idx;
    const statuses: Booking['status'][] = ['COMPLETED', 'PAID', 'REVIEWED', 'SCHEDULED', 'ON_THE_WAY', 'COMPLETED'];
    const chosenStatus = statuses[idx % statuses.length];
    return {
      id: `bk-${bookingNum}`,
      bookingNumber: `SH-2026-0${idx + 9}`,
      customerId: idx % 2 === 0 ? 'user-cust-1' : 'user-cust-3',
      customer: {
        id: idx % 2 === 0 ? 'user-cust-1' : 'user-cust-3',
        name: idx % 2 === 0 ? 'Payal Sharma' : 'Rahul Singhania',
        email: idx % 2 === 0 ? 'customer@servicehub.com' : 'rahul.s@outlook.com',
        phone: '+91 98765 43210',
      },
      providerId: idx % 3 === 0 ? 'prov-1' : idx % 3 === 1 ? 'prov-2' : 'prov-3',
      provider: {
        id: idx % 3 === 0 ? 'prov-1' : idx % 3 === 1 ? 'prov-2' : 'prov-3',
        name: idx % 3 === 0 ? 'Raj AC & Cooling Tech' : idx % 3 === 1 ? 'Suresh Electricals & Solutions' : 'Vikram Express Plumbing',
        email: 'provider@servicehub.com',
        phone: '+91 98991 12233',
        verified: true,
      },
      serviceCategoryId: idx % 3 === 0 ? 'cat-3' : idx % 3 === 1 ? 'cat-1' : 'cat-2',
      serviceCategory: idx % 3 === 0 ? 'AC Repair' : idx % 3 === 1 ? 'Electrician' : 'Plumber',
      serviceTitle: idx % 3 === 0 ? 'AC Filter Cleaning' : idx % 3 === 1 ? 'Switchboard Repair' : 'Pipe Leakage Fix',
      description: 'Scheduled regular inspection and minor maintenance repair.',
      date: `2026-09-${10 + (idx % 15)}`,
      time: `${10 + (idx % 8)}:00`,
      address: {
        street: `Plot ${15 + idx}, Civil Lines`,
        city: 'Mathura',
        area: 'Krishna Nagar',
        pincode: '281001',
      },
      estimatedCost: 499 + (idx * 50),
      finalCost: 499 + (idx * 50),
      paymentStatus: (chosenStatus === 'PAID' || chosenStatus === 'REVIEWED') ? 'PAID' as const : 'UNPAID' as const,
      status: chosenStatus,
      createdAt: `2026-09-${10 + (idx % 15)}T08:00:00Z`,
      updatedAt: `2026-09-${10 + (idx % 15)}T14:00:00Z`,
      timeline: [
        { status: 'PENDING' as const, timestamp: `2026-09-${10 + (idx % 15)}T08:00:00Z` },
        { status: 'ACCEPTED' as const, timestamp: `2026-09-${10 + (idx % 15)}T08:30:00Z` },
        { status: chosenStatus, timestamp: `2026-09-${10 + (idx % 15)}T11:00:00Z` },
      ],
    };
  }),
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    bookingId: 'bk-1003',
    customerId: 'user-cust-1',
    customerName: 'Payal Sharma',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    providerId: 'prov-3',
    providerName: 'Vikram Express Plumbing',
    rating: 5,
    comment: 'Vikram was very punctual and solved the leaking faucet within 30 minutes. Transparent pricing with no hidden charges. Highly recommended!',
    createdAt: '2026-09-28T13:00:00Z',
  },
  {
    id: 'rev-2',
    bookingId: 'bk-1007',
    customerId: 'user-cust-4',
    customerName: 'Priya Patel',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    providerId: 'prov-5',
    providerName: 'Anita Pristine Home Cleaning',
    rating: 5,
    comment: 'Outstanding deep cleaning for our 3BHK in Vrindavan! The crew was polite, wore shoe covers, and made the bathrooms sparkle like new.',
    createdAt: '2026-09-20T17:00:00Z',
  },
  {
    id: 'rev-3',
    bookingId: 'bk-1006',
    customerId: 'user-cust-1',
    customerName: 'Payal Sharma',
    customerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    providerId: 'prov-4',
    providerName: 'Manoj QuickFix Laptop & IT',
    rating: 5,
    comment: 'Saved my laptop right before an office presentation. Manoj arrived with all professional tools and replaced thermal paste right before my eyes.',
    createdAt: '2026-09-25T17:15:00Z',
  },
  {
    id: 'rev-4',
    bookingId: 'bk-1009',
    customerId: 'user-cust-2',
    customerName: 'Amit Verma',
    providerId: 'prov-1',
    providerName: 'Raj AC & Cooling Tech',
    rating: 5,
    comment: 'Best AC technician in Mathura. Excellent cooling restored. Raj explained what went wrong with the capacitor clearly.',
    createdAt: '2026-09-12T16:00:00Z',
  },
  {
    id: 'rev-5',
    bookingId: 'bk-1010',
    customerId: 'user-cust-3',
    customerName: 'Rahul Singhania',
    providerId: 'prov-2',
    providerName: 'Suresh Electricals & Solutions',
    rating: 5,
    comment: 'Suresh is an absolute pro. Fixed our fluctuating main voltage and stabilized our inverter line smoothly.',
    createdAt: '2026-09-14T11:00:00Z',
  },
  {
    id: 'rev-6',
    bookingId: 'bk-1011',
    customerId: 'user-cust-1',
    customerName: 'Payal Sharma',
    providerId: 'prov-1',
    providerName: 'Raj AC & Cooling Tech',
    rating: 4,
    comment: 'Very professional work. Arrived within 15 minutes of scheduled slot and completed the jet clean thoroughly.',
    createdAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'rev-7',
    bookingId: 'bk-1012',
    customerId: 'user-cust-4',
    customerName: 'Priya Patel',
    providerId: 'prov-3',
    providerName: 'Vikram Express Plumbing',
    rating: 4,
    comment: 'Prompt service, had genuine brass spare parts with him. Cleaned up the area after finishing.',
    createdAt: '2026-09-18T18:00:00Z',
  },
  {
    id: 'rev-8',
    bookingId: 'bk-1013',
    customerId: 'user-cust-2',
    customerName: 'Amit Verma',
    providerId: 'prov-5',
    providerName: 'Anita Pristine Home Cleaning',
    rating: 5,
    comment: 'Kitchen oil stains completely removed. Very satisfied with the service and courteous staff.',
    createdAt: '2026-09-19T15:30:00Z',
  },
  {
    id: 'rev-9',
    bookingId: 'bk-1014',
    customerId: 'user-cust-3',
    customerName: 'Rahul Singhania',
    providerId: 'prov-4',
    providerName: 'Manoj QuickFix Laptop & IT',
    rating: 4,
    comment: 'Installed SSD and upgraded RAM on my Dell laptop within an hour. Speed improved drastically.',
    createdAt: '2026-09-21T17:00:00Z',
  },
  {
    id: 'rev-10',
    bookingId: 'bk-1015',
    customerId: 'user-cust-1',
    customerName: 'Payal Sharma',
    providerId: 'prov-2',
    providerName: 'Suresh Electricals & Solutions',
    rating: 5,
    comment: 'Neat work on decorative lights and heavy chandelier mounting. Suresh checked earth leakage as well.',
    createdAt: '2026-09-22T19:00:00Z',
  },
  {
    id: 'rev-11',
    bookingId: 'bk-1016',
    customerId: 'user-cust-4',
    customerName: 'Priya Patel',
    providerId: 'prov-1',
    providerName: 'Raj AC & Cooling Tech',
    rating: 5,
    comment: 'Fixed cooling leak problem that two other technicians could not diagnose earlier. Honest pricing.',
    createdAt: '2026-09-23T14:00:00Z',
  },
  {
    id: 'rev-12',
    bookingId: 'bk-1017',
    customerId: 'user-cust-2',
    customerName: 'Amit Verma',
    providerId: 'prov-3',
    providerName: 'Vikram Express Plumbing',
    rating: 4,
    comment: 'Fitted water purifier valve and kitchen sink trap without any mess. Good communication.',
    createdAt: '2026-09-24T16:45:00Z',
  },
  {
    id: 'rev-13',
    bookingId: 'bk-1018',
    customerId: 'user-cust-3',
    customerName: 'Rahul Singhania',
    providerId: 'prov-5',
    providerName: 'Anita Pristine Home Cleaning',
    rating: 5,
    comment: 'Sofa dry clean made our living room fresh. Good fragrance and thorough dirt extraction.',
    createdAt: '2026-09-26T12:00:00Z',
  },
  {
    id: 'rev-14',
    bookingId: 'bk-1019',
    customerId: 'user-cust-1',
    customerName: 'Payal Sharma',
    providerId: 'prov-1',
    providerName: 'Raj AC & Cooling Tech',
    rating: 5,
    comment: 'Raj always provides genuine advice and fair estimates. Excellent experience through ServiceHub.',
    createdAt: '2026-09-27T15:00:00Z',
  },
  {
    id: 'rev-15',
    bookingId: 'bk-1020',
    customerId: 'user-cust-2',
    customerName: 'Amit Verma',
    providerId: 'prov-2',
    providerName: 'Suresh Electricals & Solutions',
    rating: 5,
    comment: 'Super fast response! Identified the short in external garden floodlight within 10 minutes.',
    createdAt: '2026-09-29T10:30:00Z',
  },
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-1',
    bookingId: 'bk-1001',
    customerId: 'user-cust-1',
    customerName: 'Payal Sharma',
    providerId: 'prov-1',
    providerName: 'Raj AC & Cooling Tech',
    subject: 'Delay in arrival by 20 minutes',
    description: 'Provider was delayed due to heavy traffic on Mathura highway. Service was completed properly later.',
    status: 'CLOSED',
    priority: 'LOW',
    createdAt: '2026-09-28T11:00:00Z',
    adminNotes: 'Spoke with customer and provider. Provider apologized for traffic delay. Issue resolved amicably.',
    resolution: 'Resolved through customer support call.',
  },
  {
    id: 'cmp-2',
    bookingId: 'bk-1002',
    customerId: 'user-cust-2',
    customerName: 'Amit Verma',
    providerId: 'prov-2',
    providerName: 'Suresh Electricals & Solutions',
    subject: 'Clarification regarding spare part price',
    description: 'Customer requested verification of Havells 32A MCB retail price included in final quote.',
    status: 'RESOLVED',
    priority: 'MEDIUM',
    createdAt: '2026-09-29T14:30:00Z',
    adminNotes: 'Provider submitted authentic GST invoice of the purchased switchgear. Price confirmed transparent.',
    resolution: 'Provider bill copy verified and shared with customer.',
  },
  {
    id: 'cmp-3',
    bookingId: 'bk-1005',
    customerId: 'user-cust-3',
    customerName: 'Rahul Singhania',
    providerId: 'prov-1',
    providerName: 'Raj AC & Cooling Tech',
    subject: 'Request response pending over 4 hours',
    description: 'Booking request sent in morning was not accepted or rejected within standard 2 hour SLA.',
    status: 'UNDER_REVIEW',
    priority: 'HIGH',
    createdAt: '2026-10-01T11:00:00Z',
    adminNotes: 'Notified provider via emergency dispatch. Provider was on a complex compressor overhaul job.',
  },
  {
    id: 'cmp-4',
    bookingId: 'bk-1008',
    customerId: 'user-cust-4',
    customerName: 'Priya Patel',
    providerId: 'prov-8',
    providerName: 'Deepak Drain & Pipe Care',
    subject: 'Unverified provider query',
    description: 'Customer wanted confirmation if provider verification is pending before home entry.',
    status: 'OPEN',
    priority: 'HIGH',
    createdAt: '2026-10-01T12:15:00Z',
    adminNotes: 'Reviewing Aadhaar and Police clearance documents for provider Deepak.',
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-cust-1',
    title: 'Final Price Requires Confirmation',
    message: 'Raj AC & Cooling Tech submitted final cost ₹1,049 for Booking SH-2026-001. Please review and accept.',
    type: 'WARNING',
    read: false,
    link: '/customer/bookings/bk-1001',
    createdAt: '2026-10-01T10:45:00Z',
  },
  {
    id: 'notif-2',
    userId: 'user-cust-1',
    title: 'Provider is On The Way',
    message: 'Raj Kumar is en route to Krishna Nagar for your AC repair appointment.',
    type: 'INFO',
    read: true,
    link: '/customer/bookings/bk-1001',
    createdAt: '2026-10-01T10:00:00Z',
  },
  {
    id: 'notif-3',
    userId: 'user-prov-1',
    title: 'New Service Booking Request',
    message: 'Rahul Singhania requested AC Jet Cleaning in Highway Enclave for 06:00 PM today.',
    type: 'INFO',
    read: false,
    link: '/provider/requests',
    createdAt: '2026-10-01T09:10:00Z',
  },
  {
    id: 'notif-4',
    userId: 'user-admin-1',
    title: 'New Provider Verification Pending',
    message: 'Deepak Drain & Pipe Care (Plumbing, Mathura) submitted registration documents for review.',
    type: 'ALERT',
    read: false,
    link: '/admin/provider-verification',
    createdAt: '2026-10-01T08:30:00Z',
  },
  {
    id: 'notif-5',
    userId: 'user-cust-1',
    title: 'Booking Confirmed',
    message: 'Suresh Electricals confirmed your electrical service appointment for 12 Oct, 10:30 AM.',
    type: 'SUCCESS',
    read: true,
    link: '/customer/bookings/bk-1002',
    createdAt: '2026-09-30T17:15:00Z',
  },
];
